export const DEVICE_COMMANDS = {
  TURN_ON: "TURN_ON",
  TURN_OFF: "TURN_OFF",
  SET_BRIGHTNESS: "SET_BRIGHTNESS",
  SET_TEMPERATURE: "SET_TEMPERATURE",
  SET_FAN_SPEED: "SET_FAN_SPEED",
  SET_RGB_COLOR: "SET_RGB_COLOR",
  LOCK_DOOR: "LOCK_DOOR",
  UNLOCK_DOOR: "UNLOCK_DOOR",
  OPEN_DOOR: "OPEN_DOOR",
  CLOSE_DOOR: "CLOSE_DOOR",
} as const;
